import PageShell from '../../components/PageShell';

export const metadata = {
  title: 'About',
  description: 'Why DzeNhare exists and what construction assurance means.',
};

export default function AboutPage() {
  return (
    <PageShell current="/about" compactFooter footerLeft="About page" footerRight="Governance, proof, and financial protection">
      <section className="hero simple"><div className="container hero-grid"><div><div className="eyebrow">Why DzeNhare Exists</div><h1>Construction in Zimbabwe should not depend on blind trust and financial guesswork.</h1><p>DzeNhare exists because too many projects fail before they should: the scope is wrong, the funding is weak, the contractor is underpriced, the site risks are ignored, and money moves before proof exists.</p></div><div className="panel"><div className="panel-header"><div className="panel-title">Mission</div><div className="tag green">Construction Assurance</div></div><div className="quote-box" style={{ marginTop:0 }}>Turn construction from a trust problem into a governed, verifiable financial system.</div></div></div></section>
      <section className="section"><div className="container two-col"><div><div className="eyebrow">Our View</div><h2 className="section-title">The real problem is not just building. It is decision failure around building.</h2><p className="section-subtitle">Projects fail because bad ideas are allowed through admission, bad budgets are mistaken for good ones, delays are treated as free, proof is weak, and capital is released without discipline.</p></div><div className="card"><h3>What DzeNhare stands for</h3><ul className="why-list"><li>Assurance before action</li><li>Discipline before optimism</li><li>Verification before payout</li><li>Solvency before commitment</li><li>Local intelligence before generic tooling</li></ul></div></div></section>
      <section className="section"><div className="container"><div className="eyebrow">Category</div><h2 className="section-title">DzeNhare is the decision-control and financial operating system for construction in Zimbabwe.</h2><p className="section-subtitle">That means it screens bad projects out, defends good projects against leakage and insolvency, and releases money only when math and proof agree.</p><div className="grid-3" style={{ marginTop:34 }}><div className="proof-card"><div className="proof-visual"><div className="row"><span>Discipline</span><span className="tag red" style={{ padding:'6px 10px' }}>Gate</span></div><svg viewBox="0 0 280 56" width="100%" height="56"><rect x="0" y="12" width="78" height="32" rx="11" fill="rgba(239,106,106,0.16)"/><rect x="100" y="12" width="78" height="32" rx="11" fill="rgba(241,178,74,0.16)"/><rect x="200" y="12" width="78" height="32" rx="11" fill="rgba(36,195,138,0.16)"/></svg></div><h3>We screen bad projects out</h3><p>DzeNhare is willing to say no when the economics, legality, or risk logic fail.</p></div><div className="proof-card"><div className="proof-visual"><div className="row"><span>Protection</span><span className="tag amber" style={{ padding:'6px 10px' }}>Shield</span></div><svg viewBox="0 0 280 56" width="100%" height="56"><path d="M28 42 C68 18, 108 18, 148 42 S228 58, 268 22" fill="none" stroke="#7caeff" strokeWidth="3" strokeLinecap="round"/><circle cx="148" cy="42" r="5" fill="#f1b24a"/></svg></div><h3>We defend good projects</h3><p>The platform keeps watching for leakage, delay, theft, and insolvency as the build progresses.</p></div><div className="proof-card"><div className="proof-visual"><div className="row"><span>Verification</span><span className="tag green" style={{ padding:'6px 10px' }}>Proof</span></div><svg viewBox="0 0 280 56" width="100%" height="56"><circle cx="42" cy="28" r="16" fill="rgba(124,174,255,0.18)"/><circle cx="140" cy="28" r="16" fill="rgba(241,178,74,0.18)"/><circle cx="238" cy="28" r="16" fill="rgba(36,195,138,0.18)"/><path d="M58 28h66M156 28h66" stroke="rgba(255,255,255,0.22)" strokeWidth="2.5" strokeLinecap="round"/></svg></div><h3>We release money only on proof</h3><p>The release system is governed by evidence, not pressure, assumption, or social trust.</p></div></div></div></section>
    </PageShell>
  );
}
