import PageShell from '../../components/PageShell';

export const metadata = {
  title: 'For Contractors',
  description: 'Contractor solvency tooling, pricing discipline, and better payment logic.',
};

export default function ContractorsPage() {
  return (
    <PageShell current="/contractors" compactFooter footerLeft="Contractor page" footerRight="Sell solvency, not just software">
      <section className="hero simple"><div className="container hero-grid"><div><div className="eyebrow">Contractor OS</div><h1>Quote profitably. Build solvently. Get paid under better rules.</h1><p>DzeNhare helps contractors stop underbidding, separate project cash, protect margin, and access better jobs through escrow-governed workflows and CFO-style controls.</p></div><div className="panel"><div className="panel-header"><div className="panel-title">Supply-Side Promise</div><div className="tag green">Solvency First</div></div><div className="check-list" style={{ display:'grid', gap:12, position:'relative', zIndex:1 }}><li>P4P for accurate pricing</li><li>Project Silos to stop cash mixing</li><li>Red/Green visibility before collapse</li><li>Faster release when work is verified</li></div></div></div></section>
      <section className="section"><div className="container two-col"><div><div className="eyebrow">The Real Problem</div><h2 className="section-title">Most contractors are not failing at construction. They are failing at economics.</h2><ul className="problem-list"><li>Underbidding to win work</li><li>Inflation eating margin before materials are bought</li><li>Using deposit B to finish house A</li><li>Inability to detect cash gaps early</li><li>Bad-client exposure with weak payment discipline</li></ul></div><div className="card"><h3>What DzeNhare gives you</h3><ul className="why-list"><li>P4P bid-building logic</li><li>Overhead recovery and risk buffers</li><li>Days-to-broke visibility</li><li>Project-by-project cash silos</li><li>Profit Lock discipline</li><li>Access to higher-trust clients</li></ul></div></div></section>
      <section className="section"><div className="container grid-2"><div className="proof-card"><div className="proof-visual"><div className="row"><span>P4P Margin</span><span className="tag green" style={{ padding:'6px 10px' }}>Protected</span></div><div className="score">15%</div><div className="tiny">Margin separated from direct costs and risk load.</div><svg viewBox="0 0 280 52" width="100%" height="52" aria-hidden="true" style={{ marginTop:10 }}><rect x="0" y="8" width="280" height="12" rx="6" fill="rgba(255,255,255,0.06)"/><rect x="0" y="8" width="210" height="12" rx="6" fill="rgba(36,195,138,0.55)"/><rect x="0" y="30" width="124" height="10" rx="5" fill="rgba(124,174,255,0.44)"/><rect x="136" y="30" width="90" height="10" rx="5" fill="rgba(241,178,74,0.44)"/></svg></div><h3>Stop suicide bids</h3><p>The platform forces accurate pricing instead of leaving profitability to guesswork.</p></div><div className="proof-card"><div className="proof-visual"><div className="row"><span>Cash Health</span><span className="tag amber" style={{ padding:'6px 10px' }}>12 Days</span></div><div className="score">Red/Green</div><div className="tiny">Cash gap warning before the site goes broke.</div><svg viewBox="0 0 280 52" width="100%" height="52" aria-hidden="true" style={{ marginTop:10 }}><path d="M20 42a42 42 0 0 1 84 0" fill="none" stroke="rgba(255,255,255,0.08)" strokeWidth="10" strokeLinecap="round"/><path d="M20 42a42 42 0 0 1 60 -35" fill="none" stroke="#24c38a" strokeWidth="10" strokeLinecap="round"/><path d="M62 34l22-14" stroke="#f1b24a" strokeWidth="3.5" strokeLinecap="round"/><circle cx="62" cy="34" r="4.5" fill="#f1b24a"/><text x="138" y="24" fill="#dce8ff" fontSize="10" fontFamily="Inter, sans-serif">next milestone gap</text><text x="138" y="42" fill="#a2b3c9" fontSize="10" fontFamily="Inter, sans-serif">warning before insolvency</text></svg></div><h3>See insolvency coming</h3><p>Contractors should know when the project is drifting toward danger before it becomes unrecoverable.</p></div></div></section>
      <section className="section"><div className="container"><div className="eyebrow">Maturity Path</div><h2 className="section-title">How DzeNhare helps a contractor become bankable and trusted.</h2><div className="table-card"><table><thead><tr><th>Tier</th><th>What it means</th><th>What it unlocks</th></tr></thead><tbody><tr><td><strong>Silver</strong></td><td>Verified identity and basic onboarding</td><td>Entry into the network and baseline screening</td></tr><tr><td><strong>Gold</strong></td><td>Repeated use of P4P and verified project delivery</td><td>Higher-trust client access and stronger reputation</td></tr><tr><td><strong>Platinum</strong></td><td>Strong delivery history and solvency discipline</td><td>Priority visibility and future liquidity opportunities</td></tr></tbody></table></div></div></section>
    </PageShell>
  );
}
