import Link from 'next/link';
import PageShell from '../../components/PageShell';

export const metadata = {
  title: 'For Diaspora Builders',
  description: 'Remote construction assurance for diaspora builders in Zimbabwe.',
};

export default function DiasporaBuildersPage() {
  return (
    <PageShell current="/diaspora-builders" compactFooter footerLeft="Diaspora builder page" footerRight="Built for remote control, proof, and capital protection">
      <section className="hero simple"><div className="container hero-grid"><div><div className="eyebrow">Diaspora Capital Protection</div><h1>Build in Zimbabwe without sending your money into a black hole.</h1><p>DzeNhare is designed for diaspora builders in the UK, USA, and South Africa who want proof, remote control, and defensible payment logic — not emotional reassurance and vague WhatsApp updates.</p><div className="hero-actions"><a className="btn btn-primary" href="/#start">Start project screening</a><Link className="btn btn-secondary" href="/how-it-works">See the build logic</Link></div></div><div className="panel"><div className="panel-header"><div className="panel-title">Primary Promise</div><div className="tag green">Proof Before Payment</div></div><div className="quote-box" style={{ marginTop:0 }}>Your money does not touch the contractor until the work is proven.</div></div></div></section>
      <section className="section"><div className="container two-col"><div><div className="eyebrow">What Goes Wrong</div><h2 className="section-title">The pain is not just construction. It is distance, opacity, and anxiety.</h2><ul className="problem-list"><li>Money gets diverted by family or site intermediaries</li><li>You cannot verify progress from abroad</li><li>You do not know what is actually affordable</li><li>You fear unfinished skeleton houses and fake updates</li><li>You worry inflation will destroy purchasing power before the build finishes</li></ul></div><div className="card"><h3>What DzeNhare changes</h3><ul className="why-list"><li>Screen the project before it starts</li><li>See what your wallet can truly support</li><li>Track proof artifacts before releasing money</li><li>Use an audit trail instead of verbal trust</li><li>Control milestones remotely with release logic</li></ul></div></div></section>
      <section className="section"><div className="container"><div className="eyebrow">Your Journey</div><h2 className="section-title">What the diaspora path looks like</h2><div className="timeline"><div className="step"><div className="step-num">1</div><div><h3>Run project screening</h3><p>DzeNhare checks whether the project is safe to start at all.</p></div></div><div className="step"><div className="step-num">2</div><div><h3>Get a Wallet-to-Wall verdict</h3><p>See your funding gap, max affordable scope, and phasing options before paying for the wrong design.</p></div></div><div className="step"><div className="step-num">3</div><div><h3>Lock funds under governed logic</h3><p>Escrow and release conditions keep capital ring-fenced until milestones are verified.</p></div></div><div className="step"><div className="step-num">4</div><div><h3>Approve based on proof</h3><p>Use geo-tagged progress, milestone evidence, and release state rather than blind trust.</p></div></div></div></div></section>
      <section className="section"><div className="container grid-3"><div className="proof-card"><div className="proof-visual"><div className="row"><span>Feasibility</span><span className="tag red" style={{ padding:'6px 10px' }}>NO-GO</span></div><div className="score">42%</div><div className="tiny">Stop before design costs deepen the problem.</div><svg viewBox="0 0 280 52" width="100%" height="52" aria-hidden="true" style={{ marginTop:10 }}><rect x="0" y="14" width="280" height="12" rx="6" fill="rgba(255,255,255,0.06)"/><rect x="0" y="14" width="118" height="12" rx="6" fill="rgba(239,106,106,0.62)"/><text x="0" y="46" fill="#a2b3c9" fontSize="10" fontFamily="Inter, sans-serif">max affordable scope: 65m²</text></svg></div><h3>Know the truth early</h3><p>If the project is not feasible, DzeNhare should say so clearly and early.</p></div><div className="proof-card"><div className="proof-visual"><div className="row"><span>Milestone Review</span><span className="tag green" style={{ padding:'6px 10px' }}>Verified</span></div><div className="score">3/3</div><div className="tiny">Location, image, and quality checks aligned.</div><svg viewBox="0 0 280 52" width="100%" height="52" aria-hidden="true" style={{ marginTop:10 }}><rect x="0" y="8" width="52" height="36" rx="10" fill="rgba(124,174,255,0.16)"/><rect x="64" y="8" width="52" height="36" rx="10" fill="rgba(36,195,138,0.16)"/><rect x="128" y="8" width="52" height="36" rx="10" fill="rgba(207,170,98,0.16)"/><rect x="192" y="8" width="52" height="36" rx="10" fill="rgba(36,195,138,0.22)"/></svg></div><h3>Release on evidence</h3><p>Proof should drive payment, not pressure from relatives or contractors.</p></div><div className="proof-card"><div className="proof-visual"><div className="row"><span>Escrow State</span><span className="tag amber" style={{ padding:'6px 10px' }}>Held</span></div><div className="score">$12,600</div><div className="tiny">Funds remain protected until the next gate passes.</div><svg viewBox="0 0 280 52" width="100%" height="52" aria-hidden="true" style={{ marginTop:10 }}><circle cx="40" cy="26" r="18" fill="rgba(124,174,255,0.18)" stroke="rgba(124,174,255,0.32)"/><circle cx="140" cy="26" r="18" fill="rgba(241,178,74,0.18)" stroke="rgba(241,178,74,0.32)"/><circle cx="240" cy="26" r="18" fill="rgba(36,195,138,0.18)" stroke="rgba(36,195,138,0.32)"/><path d="M58 26h64M158 26h64" stroke="rgba(255,255,255,0.22)" strokeWidth="2.5" strokeLinecap="round"/></svg></div><h3>Keep capital ring-fenced</h3><p>DzeNhare helps move money deliberately, not casually.</p></div></div></section>
    </PageShell>
  );
}
