import PageShell from '../../components/PageShell';

export const metadata = {
  title: 'For Suppliers',
  description: 'Verified demand, proof of funds, and escrow-driven supplier trust.',
};

export default function SuppliersPage() {
  return (
    <PageShell current="/suppliers" compactFooter footerLeft="Supplier page" footerRight="Verified demand, proof of funds, lower bad debt">
      <section className="hero simple"><div className="container hero-grid"><div><div className="eyebrow">Supplier Network</div><h1>Turn uncertain orders into verified demand and better payment certainty.</h1><p>DzeNhare repositions suppliers from commodity vendors chasing risky debt to value partners operating inside a governed payment and verification system.</p></div><div className="panel"><div className="panel-header"><div className="panel-title">Supplier Value Shift</div><div className="tag green">Guaranteed Payment Logic</div></div><div className="check-list" style={{ display:'grid', gap:12, position:'relative', zIndex:1 }}><li>Proof of funds before dispatch</li><li>Direct payment from escrow</li><li>Reliability score differentiation</li><li>Forward demand visibility</li></div></div></div></section>
      <section className="section"><div className="container grid-3"><div className="card"><h3>Proof-of-funds visibility</h3><p>Know when the cash is genuinely reserved for that batch of material before the truck leaves the yard.</p></div><div className="card"><h3>Reliability over price-only competition</h3><p>DzeNhare can highlight on-time performance, defect rate, and delivery trustworthiness so better suppliers are not punished for being professional.</p></div><div className="card"><h3>Demand radar</h3><p>Aggregated project flow helps suppliers anticipate demand instead of reacting only to panic orders.</p></div></div></section>
      <section className="section"><div className="container grid-2"><div className="proof-card"><div className="proof-visual"><div className="row"><span>Dispatch Readiness</span><span className="tag green" style={{ padding:'6px 10px' }}>Funded</span></div><div className="score">$4,850</div><div className="tiny">Order ring-fenced for release on verified delivery.</div><svg viewBox="0 0 280 52" width="100%" height="52" aria-hidden="true" style={{ marginTop:10 }}><circle cx="38" cy="26" r="16" fill="rgba(124,174,255,0.18)"/><circle cx="140" cy="26" r="16" fill="rgba(241,178,74,0.18)"/><circle cx="242" cy="26" r="16" fill="rgba(36,195,138,0.18)"/><path d="M54 26h70M156 26h70" stroke="rgba(255,255,255,0.22)" strokeWidth="2.5" strokeLinecap="round"/></svg></div><h3>Get better demand quality</h3><p>This reduces air supply and unpaid dispatch risk.</p></div><div className="proof-card"><div className="proof-visual"><div className="row"><span>Reliability Score</span><span className="tag amber" style={{ padding:'6px 10px' }}>98%</span></div><div className="score">On Time</div><div className="tiny">Professional performance becomes visible and rewarded.</div><svg viewBox="0 0 280 52" width="100%" height="52" aria-hidden="true" style={{ marginTop:10 }}><rect x="0" y="8" width="280" height="12" rx="6" fill="rgba(255,255,255,0.06)"/><rect x="0" y="8" width="230" height="12" rx="6" fill="rgba(36,195,138,0.55)"/><rect x="0" y="30" width="72" height="10" rx="5" fill="rgba(124,174,255,0.4)"/><rect x="84" y="30" width="90" height="10" rx="5" fill="rgba(241,178,74,0.4)"/><rect x="186" y="30" width="88" height="10" rx="5" fill="rgba(36,195,138,0.3)"/></svg></div><h3>Differentiate on trust, not just price</h3><p>The long-term moat is not a cheap list of suppliers. It is a scored supply network.</p></div></div></section>
    </PageShell>
  );
}
