import PageShell from '../../components/PageShell';

export const metadata = {
  title: 'How It Works',
  description: 'How DzeNhare governs the construction lifecycle from screening to release.',
};

export default function HowItWorksPage() {
  return (
    <PageShell current="/how-it-works" compactFooter footerLeft="DzeNhare lifecycle page" footerRight="Admission → feasibility → escrow → verification → release">
      <section className="hero simple"><div className="container hero-grid"><div><div className="eyebrow">Governed Lifecycle</div><h1>How DzeNhare controls the build from first screening to final release.</h1><p>DzeNhare is not a passive dashboard layered on top of construction chaos. It is an operating logic that governs whether the project starts, how it phases, when money moves, what gets verified, and how risk is handled while execution is live.</p></div><div className="panel"><div className="panel-header"><div className="panel-title">Lifecycle Logic</div><div className="status-badge" style={{ background:'var(--green-soft)', color:'#9df0cf', borderColor:'rgba(36,195,138,0.22)' }}><span className="dot"></span> VERIFIED FLOW</div></div><div className="check-list" style={{ display:'grid', gap:12, position:'relative', zIndex:1 }}><li>Admission before design</li><li>Feasibility before commitment</li><li>Escrow before disbursement</li><li>Verification before release</li><li>Audit trail before closure</li></div></div></div></section>
      <section className="section"><div className="container"><div className="timeline">
        <div className="step"><div className="step-num">1</div><div><h3>Project admission</h3><p>Every project begins with Go / No-Go logic. DzeNhare checks funding readiness, legal compliance, title clarity, local kill factors, soil exposure, and risk-adjusted affordability before the build is allowed to progress.</p><div className="proof-visual" style={{ minHeight:120, marginTop:16 }}><svg viewBox="0 0 320 68" width="100%" height="68"><rect x="8" y="14" width="92" height="40" rx="12" fill="rgba(124,174,255,0.16)"/><rect x="114" y="14" width="92" height="40" rx="12" fill="rgba(241,178,74,0.16)"/><rect x="220" y="14" width="92" height="40" rx="12" fill="rgba(239,106,106,0.16)"/></svg></div></div></div>
        <div className="step"><div className="step-num">2</div><div><h3>Feasibility and phasing</h3><p>Wallet-to-Wall compares real capital to real project cost. If the scope is too large, the platform recommends phasing, max affordable area, or a safer first-build strategy rather than pretending the dream is already funded.</p><div className="proof-visual" style={{ minHeight:120, marginTop:16 }}><svg viewBox="0 0 320 68" width="100%" height="68"><rect x="12" y="20" width="296" height="12" rx="6" fill="rgba(255,255,255,0.06)"/><rect x="12" y="20" width="124" height="12" rx="6" fill="rgba(239,106,106,0.6)"/><text x="12" y="54" fill="#a2b3c9" fontSize="10" fontFamily="Inter, sans-serif">Funding ratio drives phasing and scope correction</text></svg></div></div></div>
        <div className="step"><div className="step-num">3</div><div><h3>Budget and pricing structure</h3><p>Contractor-side pricing and solvency logic ensures bids are economically valid. P4P, overhead recovery, risk buffers, and startup cash needs are made explicit before the job is priced or accepted.</p><div className="proof-visual" style={{ minHeight:120, marginTop:16 }}><svg viewBox="0 0 320 68" width="100%" height="68"><rect x="10" y="10" width="90" height="14" rx="7" fill="rgba(124,174,255,0.45)"/><rect x="10" y="30" width="180" height="14" rx="7" fill="rgba(36,195,138,0.5)"/><rect x="10" y="50" width="140" height="10" rx="5" fill="rgba(241,178,74,0.45)"/></svg></div></div></div>
        <div className="step"><div className="step-num">4</div><div><h3>Escrow setup and fund control</h3><p>Project funds are ring-fenced. Money is not treated like an informal deposit sitting in someone’s pocket. DzeNhare establishes release rules tied to milestones, evidence, procurement events, and quality checks.</p><div className="proof-visual" style={{ minHeight:120, marginTop:16 }}><svg viewBox="0 0 320 68" width="100%" height="68"><circle cx="48" cy="34" r="16" fill="rgba(124,174,255,0.18)"/><circle cx="160" cy="34" r="16" fill="rgba(241,178,74,0.18)"/><circle cx="272" cy="34" r="16" fill="rgba(36,195,138,0.18)"/><path d="M64 34h80M176 34h80" stroke="rgba(255,255,255,0.22)" strokeWidth="2.5" strokeLinecap="round"/></svg></div></div></div>
        <div className="step"><div className="step-num">5</div><div><h3>Procurement and delivery</h3><p>Suppliers can receive proof-of-funds signals, direct-pay logic, and verified demand. DzeNhare helps reduce bad debt and improve material flow through supplier reliability, proof-of-delivery, and coordinated buying logic.</p><div className="proof-visual" style={{ minHeight:120, marginTop:16 }}><svg viewBox="0 0 320 68" width="100%" height="68"><rect x="12" y="18" width="140" height="14" rx="7" fill="rgba(36,195,138,0.45)"/><rect x="12" y="40" width="220" height="14" rx="7" fill="rgba(124,174,255,0.34)"/></svg></div></div></div>
        <div className="step"><div className="step-num">6</div><div><h3>Verification and execution monitoring</h3><p>Geo-tagged progress, variance tracking, material detective logic, and slippage-cost monitoring keep the project economically honest while it is live. If execution leaks appear, they surface early enough to act on.</p><div className="proof-visual" style={{ minHeight:120, marginTop:16 }}><svg viewBox="0 0 320 68" width="100%" height="68"><path d="M10 52 C60 34, 92 26, 140 40 S220 62, 310 20" fill="none" stroke="#7caeff" strokeWidth="3" strokeLinecap="round"/><circle cx="220" cy="47" r="5" fill="#f1b24a"/></svg></div></div></div>
        <div className="step"><div className="step-num">7</div><div><h3>Milestone release</h3><p>Money moves only when the release conditions pass. DzeNhare uses milestone verification, proof artifacts, and release-state logic so payment is governed by evidence, not social pressure.</p><div className="proof-visual" style={{ minHeight:120, marginTop:16 }}><svg viewBox="0 0 320 68" width="100%" height="68"><rect x="14" y="16" width="70" height="36" rx="12" fill="rgba(124,174,255,0.16)"/><rect x="126" y="16" width="70" height="36" rx="12" fill="rgba(36,195,138,0.16)"/><rect x="238" y="16" width="70" height="36" rx="12" fill="rgba(207,170,98,0.16)"/></svg></div></div></div>
        <div className="step"><div className="step-num">8</div><div><h3>Handover and audit trail</h3><p>The end state is not just project completed. It is a traceable record of what happened, what was paid, what was verified, what was delayed, and how decisions were made throughout the build.</p><div className="proof-visual" style={{ minHeight:120, marginTop:16 }}><svg viewBox="0 0 320 68" width="100%" height="68"><rect x="10" y="10" width="300" height="48" rx="14" fill="rgba(255,255,255,0.04)"/><path d="M30 26h110M30 40h180M30 54h140" stroke="rgba(255,255,255,0.18)" strokeWidth="3" strokeLinecap="round"/></svg></div></div></div>
      </div></div></section>
      <section className="section"><div className="container"><div className="eyebrow">Why This Matters</div><h2 className="section-title">The system is designed to stop optimism from outrunning economics.</h2><div className="grid-3" style={{ marginTop:34 }}><div className="card"><h3>For clients</h3><p>It replaces blind remittance and verbal updates with project logic you can inspect and approve remotely.</p></div><div className="card"><h3>For contractors</h3><p>It reduces underpricing, cash-flow confusion, and bad-client exposure by forcing solvency discipline.</p></div><div className="card"><h3>For suppliers</h3><p>It turns vague orders into higher-trust demand through proof-of-funds and controlled release mechanics.</p></div></div></div></section>
    </PageShell>
  );
}
